"""Compliance report generation (PDF + HTML).

HTML is always available (no dependencies). PDF uses reportlab when installed.
Both render the same content: header, compliance verdict, findings table, AI
advisory, recommendations and legal references.
"""

from __future__ import annotations

import html
from typing import Any

_STATUS_COLOR = {"pass": "#15803d", "warning": "#b45309", "fail": "#b91c1c"}
_RISK_COLOR = {"low": "#15803d", "medium": "#b45309", "high": "#b91c1c"}


def _g(d: dict, *keys, default=""):
    for k in keys:
        d = d.get(k, {}) if isinstance(d, dict) else {}
    return d if d != {} else default


def build_html(review: dict[str, Any]) -> str:
    result = review.get("result_json", {})
    invoice = review.get("invoice_json", {})
    advisory = review.get("advisory_json", {})
    status = (result.get("compliance_status") or "warning").lower()
    risk = (result.get("risk_level") or "low").lower()

    findings_rows = "".join(
        f"""<tr>
            <td>{html.escape(str(f.get('rule_id','')))}</td>
            <td><span class="sev sev-{f.get('severity','')}">{html.escape(str(f.get('severity','')))}</span></td>
            <td>{html.escape(str(f.get('title','')))}</td>
            <td>{html.escape(str(f.get('detail','')))}</td>
            <td>{html.escape(str(f.get('legal_ref','') or ''))}</td>
        </tr>"""
        for f in result.get("findings", [])
    ) or '<tr><td colspan="5">No findings.</td></tr>'

    recs = "".join(f"<li>{html.escape(str(r))}</li>" for r in advisory.get("recommendations", []))
    cites = "".join(f"<li>{html.escape(str(c))}</li>" for c in advisory.get("citations", []))

    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>VAT Compliance Report</title>
<style>
  body {{ font-family: 'Segoe UI', Arial, sans-serif; color:#1f2937; margin:40px; }}
  h1 {{ font-size:22px; margin-bottom:0; }}
  .sub {{ color:#6b7280; margin-top:4px; }}
  .badges span {{ display:inline-block; padding:6px 12px; border-radius:6px; color:#fff;
                  font-weight:600; margin-right:8px; }}
  table {{ width:100%; border-collapse:collapse; margin:14px 0; font-size:13px; }}
  th,td {{ border:1px solid #e5e7eb; padding:8px; text-align:left; vertical-align:top; }}
  th {{ background:#f9fafb; }}
  .sev {{ padding:2px 8px; border-radius:4px; color:#fff; font-size:11px; text-transform:uppercase; }}
  .sev-high {{ background:#b91c1c; }} .sev-medium {{ background:#b45309; }}
  .sev-low {{ background:#2563eb; }} .sev-info {{ background:#6b7280; }}
  .card {{ background:#f9fafb; border:1px solid #e5e7eb; border-radius:8px; padding:16px; margin:14px 0; }}
  footer {{ margin-top:30px; color:#9ca3af; font-size:11px; }}
</style></head><body>
  <h1>UAE VAT Compliance Report</h1>
  <div class="sub">Invoice {html.escape(str(invoice.get('invoice_number','—')))} ·
       {html.escape(str(invoice.get('invoice_date','—')))} ·
       Supplier: {html.escape(str((invoice.get('supplier') or {}).get('name','—')))}</div>

  <div class="badges" style="margin:18px 0;">
     <span style="background:{_STATUS_COLOR.get(status,'#6b7280')}">Status: {status.upper()}</span>
     <span style="background:{_RISK_COLOR.get(risk,'#6b7280')}">Risk: {risk.upper()}</span>
  </div>

  <p>{html.escape(str(result.get('summary','')))}</p>

  <h3>Findings</h3>
  <table>
    <tr><th>Rule</th><th>Severity</th><th>Title</th><th>Detail</th><th>Legal basis</th></tr>
    {findings_rows}
  </table>

  <h3>AI Consultant Advisory</h3>
  <div class="card">{html.escape(str(advisory.get('narrative',''))).replace(chr(10),'<br>')}</div>

  <h3>Recommended actions</h3>
  <ul>{recs or '<li>—</li>'}</ul>

  <h3>Legal references relied upon</h3>
  <ul>{cites or '<li>—</li>'}</ul>

  <footer>
    Generated by the UAE VAT Compliance Platform. Verdicts are produced by a
    deterministic rule engine grounded in Federal Decree-Law No. 8 of 2017 and its
    Executive Regulation. This report is a compliance aid, not a substitute for a
    formal FTA ruling.
  </footer>
</body></html>"""


def build_pdf(review: dict[str, Any]) -> bytes | None:
    """Render the report to PDF using reportlab. Returns None if reportlab is absent."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import (
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except Exception:  # noqa: BLE001
        return None

    import io

    result = review.get("result_json", {})
    invoice = review.get("invoice_json", {})
    advisory = review.get("advisory_json", {})

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="UAE VAT Compliance Report")
    styles = getSampleStyleSheet()
    flow = [
        Paragraph("UAE VAT Compliance Report", styles["Title"]),
        Paragraph(
            f"Invoice {invoice.get('invoice_number','—')} · "
            f"Status <b>{(result.get('compliance_status') or '').upper()}</b> · "
            f"Risk <b>{(result.get('risk_level') or '').upper()}</b>",
            styles["Normal"],
        ),
        Spacer(1, 10),
        Paragraph(result.get("summary", ""), styles["Normal"]),
        Spacer(1, 12),
        Paragraph("Findings", styles["Heading2"]),
    ]

    data = [["Rule", "Severity", "Title", "Legal basis"]]
    for f in result.get("findings", []):
        data.append(
            [f.get("rule_id", ""), f.get("severity", ""), f.get("title", ""), f.get("legal_ref", "") or ""]
        )
    table = Table(data, colWidths=[70, 55, 200, 150])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    flow += [table, Spacer(1, 14), Paragraph("AI Consultant Advisory", styles["Heading2"])]
    flow.append(Paragraph((advisory.get("narrative", "") or "—").replace("\n", "<br/>"), styles["Normal"]))

    if advisory.get("recommendations"):
        flow += [Spacer(1, 10), Paragraph("Recommended actions", styles["Heading2"])]
        for r in advisory["recommendations"]:
            flow.append(Paragraph(f"• {r}", styles["Normal"]))

    doc.build(flow)
    return buf.getvalue()


# ── Comprehensive combined report ────────────────────────────────────────────
def _esc(v) -> str:
    if v in (None, ""):
        return "—"
    return html.escape(str(v))


def build_vat311_pdf(app: dict[str, Any]) -> bytes | None:
    """FTA VAT311 — VAT Refund Application form."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except Exception:  # noqa: BLE001
        return None

    import io

    styles = getSampleStyleSheet()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="VAT311 — VAT Refund Application",
                            leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm)
    flow = [
        Paragraph("VAT Refund Application — Form VAT311", styles["Title"]),
        Paragraph("United Arab Emirates · Federal Tax Authority", styles["Normal"]),
        Spacer(1, 8),
        HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#0f5b9e")),
        Spacer(1, 8),
    ]

    def kv(rows):
        t = Table([[Paragraph(f"<b>{_esc(k)}</b>", styles["Normal"]), Paragraph(_esc(v), styles["Normal"])]
                   for k, v in rows], colWidths=[85 * mm, None])
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5), ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#e5e7eb")),
        ]))
        return t

    flow.append(Paragraph("Taxable person", styles["Heading3"]))
    flow.append(kv([
        ("Tax Registration Number (TRN)", app.get("trn")),
        ("Legal name of entity", app.get("legal_name")),
        ("Tax period of the return", app.get("period_label")),
    ]))
    flow.append(Spacer(1, 8))

    flow.append(Paragraph("Refund details (AED)", styles["Heading3"]))
    flow.append(kv([
        ("Total amount of excess refundable tax", app.get("total_excess_refundable")),
        ("The amount you wish to have refunded", app.get("amount_requested")),
        ("Remaining amount of eligible excess refundable tax", app.get("remaining_excess")),
        ("Late registration penalty payable (if any)", app.get("late_registration_penalty")),
        ("Net refund expected (after penalty offset)", app.get("net_refund_expected")),
    ]))
    flow.append(Spacer(1, 10))

    flow.append(Paragraph("Declaration", styles["Heading3"]))
    flow.append(Paragraph(
        "I declare that the information provided in this application is true, correct and "
        "complete. I understand the FTA may offset any outstanding liabilities or penalties "
        "against the refund.", styles["Normal"]))
    flow.append(Spacer(1, 14))
    flow.append(kv([
        ("Authorized signatory", app.get("authorized_signatory")),
        ("Date", app.get("declaration_date") or app.get("generated_at")),
        ("Signature", ""),
    ]))
    flow.append(Spacer(1, 12))
    flow.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#d1d5db")))
    flow.append(Paragraph(
        "Prepared by the UAE VAT Compliance Platform from the VAT201 return. Submit via the "
        "EmaraTax portal; the FTA remains the authority for the refund decision.",
        styles["Normal"]))
    doc.build(flow)
    return buf.getvalue()


def build_vat201_pdf(ret: dict[str, Any]) -> bytes | None:
    """Print-ready VAT201 return summary."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    except Exception:  # noqa: BLE001
        return None

    import io

    styles = getSampleStyleSheet()
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, title="UAE VAT Return (VAT201)",
                            leftMargin=16 * mm, rightMargin=16 * mm, topMargin=16 * mm)
    flow: list = [
        Paragraph("UAE VAT Return — VAT201", styles["Title"]),
        Paragraph(
            f"{_esc(ret.get('company_name'))} · TRN {_esc(ret.get('company_trn'))} · "
            f"Period {_esc(ret.get('period_label'))} · Due {_esc(ret.get('due_date'))}",
            styles["Normal"],
        ),
        Spacer(1, 8),
    ]
    totals = ret.get("totals", {})
    verdict = "REFUND" if totals.get("is_refund") else "PAYABLE"
    flow.append(Paragraph(
        f"<b>Net VAT {verdict}: AED {_esc(totals.get('net_vat_due'))}</b> "
        f"(output {_esc(totals.get('output_vat'))} − recoverable {_esc(totals.get('recoverable_input_vat'))})",
        styles["Normal"],
    ))
    flow.append(Spacer(1, 10))

    data = [["Box", "Description", "Amount (AED)", "VAT (AED)"]]
    for b in ret.get("boxes", []):
        data.append([b["box"], b["label"], b["amount"], b["vat"]])
    table = Table(data, colWidths=[32, None, 70, 70])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f5b9e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d1d5db")),
        ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
        # Emphasise total rows.
        ("BACKGROUND", (0, 8), (-1, 8), colors.HexColor("#eef2f7")),
        ("BACKGROUND", (0, 11), (-1, 11), colors.HexColor("#eef2f7")),
        ("BACKGROUND", (0, 14), (-1, 14), colors.HexColor("#dbeafe")),
    ]))
    flow.append(table)

    issues = ret.get("validations", [])
    if issues:
        flow.append(Spacer(1, 10))
        flow.append(Paragraph("Validation", styles["Heading3"]))
        for v in issues[:40]:
            flow.append(Paragraph(f"• [{_esc(v.get('severity','').upper())}] {_esc(v.get('message'))}", styles["Normal"]))

    flow.append(Spacer(1, 12))
    flow.append(Paragraph(
        "Generated by the UAE VAT Compliance Platform. Figures are computed from the "
        "supplied transactions; review before filing on EmaraTax within 28 days of period end.",
        styles["Normal"],
    ))
    doc.build(flow)
    return buf.getvalue()


def build_report_pdf(review: dict[str, Any]) -> bytes | None:
    """Full per-document review report combining the original document metadata,
    extracted data, compliance verdict, AI advisory, findings, risks and
    recommendations. Returns None if reportlab is unavailable."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import mm
        from reportlab.platypus import (
            HRFlowable,
            Paragraph,
            SimpleDocTemplate,
            Spacer,
            Table,
            TableStyle,
        )
    except Exception:  # noqa: BLE001
        return None

    import io

    inv = review.get("invoice_json") or {}
    result = review.get("result_json") or {}
    advisory = review.get("advisory_json") or {}
    meta = review.get("meta") or {}
    sup = inv.get("supplier") or {}
    rec = inv.get("recipient") or {}
    pay = inv.get("payment") or {}

    status = (result.get("compliance_status") or meta.get("compliance_status") or "").lower()
    risk = (result.get("risk_level") or meta.get("risk_level") or "").lower()
    status_color = colors.HexColor(_STATUS_COLOR.get(status, "#6b7280"))
    risk_color = colors.HexColor(_RISK_COLOR.get(risk, "#6b7280"))

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#6b7280")))
    styles.add(ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=13))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=12, spaceBefore=10, spaceAfter=4,
                        textColor=colors.HexColor("#0f5b9e"))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4, title="UAE VAT Compliance Review Report",
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
    )
    flow: list = []

    def P(text, style="Body"):
        return Paragraph(text, styles[style] if isinstance(style, str) else style)

    def section(title):
        flow.append(P(title, h2))
        flow.append(HRFlowable(width="100%", thickness=0.6, color=colors.HexColor("#0f5b9e"), spaceAfter=6))

    def kv_table(rows, col1=45 * mm):
        t = Table([[P(f"<b>{k}</b>", "Small"), P(_esc(v), "Body")] for k, v in rows],
                  colWidths=[col1, None])
        t.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.HexColor("#eef0f3")),
        ]))
        return t

    # ── Title ────────────────────────────────────────────────────────────────
    flow.append(P("UAE VAT Compliance Review Report", styles["Title"]))
    flow.append(P(
        f"Report generated: {_esc(meta.get('report_generated_at'))} · "
        f"Review ID: {_esc(meta.get('id'))}", "Small"))
    flow.append(Spacer(1, 8))

    # ── Verdict banner ─────────────────────────────────────────────────────────
    banner = Table(
        [[P("<b>COMPLIANCE STATUS</b>", "Small"), P("<b>RISK LEVEL</b>", "Small"), P("<b>REVIEW STATUS</b>", "Small")],
         [P(f"<b>{_esc(status.upper())}</b>"), P(f"<b>{_esc(risk.upper())}</b>"), P(_esc((meta.get('status') or '').upper()))]],
        colWidths=[None, None, None])
    banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ("TEXTCOLOR", (0, 1), (0, 1), status_color),
        ("TEXTCOLOR", (1, 1), (1, 1), risk_color),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    flow.append(banner)
    flow.append(Spacer(1, 6))
    flow.append(P(_esc(result.get("summary")), "Body"))

    # ── 1. Original document & metadata ───────────────────────────────────────
    section("1 · Original Document & Metadata")
    flow.append(kv_table([
        ("File name", meta.get("filename")),
        ("Document type", (review.get("doc_type") or meta.get("doc_type") or inv.get("invoice_type"))),
        ("Text capture", f"OCR ({meta.get('ocr_engine')})" if meta.get("ocr_used") else "Native text layer"),
        ("Uploaded", meta.get("created_at")),
        ("Last updated", meta.get("updated_at")),
    ]))

    # ── 2. Extracted invoice data ──────────────────────────────────────────────
    section("2 · Extracted Invoice Data")
    flow.append(kv_table([
        ("Invoice number", inv.get("invoice_number")),
        ("Invoice date", inv.get("invoice_date")),
        ("Due date", inv.get("due_date")),
        ("Currency", inv.get("currency")),
        ("Supplier", sup.get("name")),
        ("Supplier TRN", sup.get("trn")),
        ("Supplier address", sup.get("address")),
        ("Customer", rec.get("name")),
        ("Customer TRN", rec.get("trn")),
        ("Customer address", rec.get("address")),
        ("Total (net)", inv.get("total_net")),
        ("Total VAT", inv.get("total_vat")),
        ("Total (gross)", inv.get("total_gross")),
    ]))

    items = inv.get("line_items") or []
    if items:
        flow.append(Spacer(1, 6))
        flow.append(P("<b>Line items</b>", "Small"))
        data = [["Description", "Net", "VAT rate", "VAT", "Total"]]
        for li in items:
            data.append([
                _esc(li.get("description")), _esc(li.get("net_amount")), _esc(li.get("vat_rate")),
                _esc(li.get("vat_amount")), _esc(li.get("line_total")),
            ])
        t = Table(data, colWidths=[None, 60, 45, 55, 60])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d1d5db")),
            ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ]))
        flow.append(t)

    if any(pay.values()) if isinstance(pay, dict) else False:
        flow.append(Spacer(1, 6))
        flow.append(kv_table([
            ("Bank", pay.get("bank_name")), ("Account name", pay.get("account_name")),
            ("Account no.", pay.get("account_number")), ("IBAN", pay.get("iban")),
            ("SWIFT", pay.get("swift")),
        ]))

    # ── 3. Compliance review (rule engine) ─────────────────────────────────────
    section("3 · Compliance Review (Deterministic Rule Engine)")
    findings = result.get("findings") or []
    if findings:
        data = [["Rule", "Severity", "Finding", "Legal basis"]]
        for f in findings:
            data.append([
                _esc(f.get("rule_id")),
                _esc((f.get("severity") or "").upper()),
                P(f"<b>{_esc(f.get('title'))}</b><br/>{_esc(f.get('detail'))}", "Small"),
                P(_esc(f.get("legal_ref")), "Small"),
            ])
        t = Table(data, colWidths=[60, 48, None, 95])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#d1d5db")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        flow.append(t)
    else:
        flow.append(P("No rule violations were found against the mandatory VAT particulars checked."))

    # ── 4. Key findings & risks ────────────────────────────────────────────────
    key = [f for f in findings if (f.get("severity") or "") in ("high", "medium")]
    if key:
        section("4 · Key Findings & Identified Risks")
        for f in key:
            flow.append(P(f"• <b>[{_esc((f.get('severity') or '').upper())}]</b> {_esc(f.get('title'))} — {_esc(f.get('detail'))}"))

    # ── Data validation cross-checks ───────────────────────────────────────────
    validations = result.get("validations") or []
    if validations:
        section("Data Validation")
        for c in validations:
            mark = "PASS" if c.get("passed") else "FAIL"
            flow.append(P(f"• [{mark}] {_esc(c.get('name'))} — {_esc(c.get('detail'))}"))

    # ── Fields requiring verification (extraction gaps, not compliance failures) ─
    verification = result.get("verification_items") or []
    if verification:
        section("Fields Requiring Verification")
        flow.append(P(
            "The following fields were not confidently auto-extracted. They are flagged for "
            "manual verification and do <b>not</b>, by themselves, affect the Pass/Fail verdict.",
            "Small",
        ))
        for v in verification:
            state = (
                f"low confidence {round(float(v.get('confidence', 0)) * 100)}%"
                if v.get("status") == "low_confidence"
                else ("not detected — likely present" if v.get("likely_present") else "not detected")
            )
            flow.append(P(f"• {_esc(v.get('label'))} — <i>{state}</i>. {_esc(v.get('reason'))}"))

    # ── 5. AI analysis & advisory ──────────────────────────────────────────────
    section("5 · AI Analysis & Advisory")
    prov = advisory.get("provider") or "—"
    llm = "LLM-generated" if advisory.get("llm_used") else "Deterministic (no LLM)"
    flow.append(P(f"<b>Source:</b> {_esc(prov)} ({llm}) · <b>Confidence:</b> {_esc(advisory.get('confidence'))}", "Small"))
    if advisory.get("error"):
        flow.append(P(f"<i>AI note: {_esc(advisory.get('error'))}</i>", "Small"))
    flow.append(Spacer(1, 3))
    flow.append(P(_esc(advisory.get("narrative")).replace("\n", "<br/>")))

    # ── 6. Recommendations ─────────────────────────────────────────────────────
    recs = list(advisory.get("recommendations") or [])
    for f in findings:
        if f.get("recommendation") and f["recommendation"] not in recs:
            recs.append(f["recommendation"])
    if recs:
        section("6 · Recommendations & Suggested Actions")
        for r in recs:
            flow.append(P(f"• {_esc(r)}"))

    # ── 7. Final verdict ───────────────────────────────────────────────────────
    section("7 · Final Compliance Verdict")
    flow.append(P(
        f"This document is assessed as <b>{_esc(status.upper())}</b> with "
        f"<b>{_esc(risk.upper())}</b> compliance risk by the deterministic rule engine, "
        f"which remains the authoritative verdict. The verdict is based on the actual invoice "
        f"data; fields that could not be extracted are flagged for verification and do not "
        f"themselves cause a failure. Review workflow status: "
        f"<b>{_esc((meta.get('status') or '').upper())}</b>."))
    if result.get("verification_items"):
        flow.append(P(
            f"⚠ {len(result['verification_items'])} field(s) require manual verification "
            "before this review is finalised.", "Small"))

    flow.append(Spacer(1, 12))
    flow.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#d1d5db")))
    flow.append(P(
        "Generated by the UAE VAT Compliance Platform. Compliance verdicts are produced by a "
        "deterministic rule engine grounded in Federal Decree-Law No. 8 of 2017 and its Executive "
        "Regulation. This report is a compliance aid, not a formal FTA ruling.", "Small"))

    doc.build(flow)
    return buf.getvalue()
